package com.example.TPXProj.models;

import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;

/**
 * Object representation of a database nonprofit tuple.
 * Includes getters and setters for database object.
 *
 * @author Caleb Warner
 */
@Entity
public class DatabaseNonprofit {
    // *************************************************************************
    // Fields
    // *************************************************************************
    /** Primary key for table. Generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private int id;

    /** String name for nonprofit. */
    private String name;

    /** String website for nonprofit. */
    private String website;

    /** String phone for nonprofit. */
    private String phone;

    /** String email for nonprofit. */
    private String email;

    /** String pseudo-binary number of needs for nonprofit. */
    private String needs;

    /** String pseudo-binary number of activities for nonprofit. */
    private String activities;

    /** String pseudo-binary number of skills for nonprofit. */
    private String skills;

    /** String pseudo-binary number of commitments for nonprofit. */
    private String commitments;

    /** int location for nonprofit. */
    private int location;


    // *************************************************************************
    // Public Methods
    // *************************************************************************
    /**
     * Getter for id field
     *
     * @return id stored in field
     */
    public int getID() {
        return id;
    } // public int getID()

    /**
     * Setter for id field
     *
     * @param id value to be assigned
     */
    public void setId(int id) {
        this.id = id;
    } // public void setId()

    /**
     * Getter for name field
     *
     * @return name stored in field
     */
    public String getName() {
        return name;
    } // public String getName()

    /**
     * Setter for name field
     *
     * @param name value to be assigned
     */
    public void setName(String name) {
        this.name = name;
    } // public void setName()

    /**
     * Getter for website field
     *
     * @return website stored in field
     */
    public String getWebsite() {
        return website;
    } // public String getWebsite()

    /**
     * Setter for website field
     *
     * @param website value to be assigned
     */
    public void setWebsite(String website) {
        this.website = website;
    } // public void setWebsite()

    /**
     * Getter for phone field
     *
     * @return phone stored in field
     */
    public String getPhone() {
        return phone;
    } // public String getPhone()

    /**
     * Setter for phone field
     *
     * @param phone value to be assigned
     */
    public void setPhone(String phone) {
        this.phone = phone;
    } // public void setPhone()

    /**
     * Getter for email field
     *
     * @return email stored in field
     */
    public String getEmail() {
        return email;
    } // public String getEmail()

    /**
     * Setter for email field
     *
     * @param email value to be assigned
     */
    public void setEmail(String email) {
        this.email = email;
    } // public void setEmail()

    /**
     * Getter for needs field
     *
     * @return needs stored in field
     */
    public String getNeeds() {
        return needs;
    } // public String getNeeds()

    /**
     * Setter for needs field
     *
     * @param needs value to be assigned
     */
    public void setNeeds(String needs) {
        this.needs = needs;
    } // public void setNeeds()

    /**
     * Getter for activities field
     *
     * @return activities stored in field
     */
    public String getActivities() {
        return activities;
    } // public String getActivities()

    /**
     * Setter for activities field
     *
     * @param activities value to be assigned
     */
    public void setActivities(String activities) {
        this.activities = activities;
    } // public void setActivities()

    /**
     * Getter for skills field
     *
     * @return skills stored in field
     */
    public String getSkills() {
        return skills;
    } // public String getSkills()

    /**
     * Setter for skills field
     *
     * @param skills value to be assigned
     */
    public void setSkills(String skills) {
        this.skills = skills;
    } // public void setSkills()

    /**
     * Getter for commitments field
     *
     * @return commitments stored in field
     */
    public String getCommitments() {
        return commitments;
    } // public String getCommitments()

    /**
     * Setter for commitments field
     *
     * @param commitments value to be assigned
     */
    public void setCommitments(String commitments) {
        this.commitments = commitments;
    } // public void setCommitments()

    /**
     * Getter for location field
     *
     * @return location stored in field
     */
    public int getLocation() {
        return location;
    } // public int getLocation()

    /**
     * Setter for location field
     *
     * @param location value to be assigned
     */
    public void setLocation(int location) {
        this.location = location;
    } // public void setLocation()
} // public class DatabaseNonprofit